name: Daily Python Email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Environment
        run: |
          # Additional setup, e.g., installing utility package
          pip install utility_package  # Replace with the actual name of your utility package
      - name: Test with pytest
        run: |
          pytest
      - name: Run Python Script
        run: |
          API_KEY=$API_KEY python main.py
