name: Daily Flask Build and Test

on:
  workflow_dispatch:  # This triggers the workflow manually
  schedule:
    - cron: '0 5 * * *'  # Run every day at 5 AM UTC (adjust as needed for Norway time)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Environment
        run: |
          # Additional setup, e.g., installing utility package
          pip install utility_package  # Replace with the actual name of your utility package
      - name: Test with pytest
        run: |
          pytest
      - name: Run Python Script
        run: |
          python main.py
